baseURL = "/"
languageCode = "fr-fr"
title = "Docdock"
theme = "hugo-theme-docdock"
#themesdir = "../.."

[params]
editURL = "https://github.com/ChristopheDucamp/docdock/edit/master/content/"
noHomeIcon = false
noSearch = false

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>Plus</h3>"
name = "<i class='fa fa-github'></i> dépôt Github"
identifier = "ds"
url = "https://github.com/ChristopheDucamp/docdock"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa fa-bookmark'></i> Documentation Hugo"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 2
